[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "reading_list"
version = "1.2.4"
authors = [
    { name = "Your Name" }
]
description = "A Python-based application to track reading habits"
dependencies = [
    "sqlalchemy",
    "alembic",
    "pandas",
    "xlsxwriter",
    "openpyxl",
    "tabulate>=0.9.0"
]
requires-python = ">=3.8"

[tool.setuptools]
packages = ["src"]
package-dir = {"" = "."}
