[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "reading_list"
version = "1.3.0"
description = "Reading List Tracker"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
requires-python = ">=3.8"
dependencies = [
    "sqlalchemy",
    "alembic",
    "pandas",
    "xlsxwriter",
    "openpyxl",
    "tabulate>=0.9.0",
    "termcolor",
    "rich"
]

[tool.setuptools]
packages = ["src", "scripts"]
package-dir = {"" = "."}

[tool.pytest.ini_options]
pythonpath = [
    "."
]
